# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Hacked Jekyll
description: Jekyll microtheme that looks like JSON
baseurl: ""
url: https://hacked-jekyll.netlify.app

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Virgil Sisoe
  description:
    - VFX Wizard--Hacking Visuals
    - Chaos to Code
    - Script Magic Unleashed
    - Tech Riddles? Solved.
    - Frame by Frame--Visual Exploits
  # cv: assets/cv.pdf
  address:
    - New York
  contact:
    email: virgilsisoe@outlook.com
  profiles:
    instagram: https://www.instagram.com/soe.blend
    linkedin: https://www.linkedin.com/in/virgilsisoe
    github: https://github.com/sisoe24/

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never
